package Chat;


/**
* Chat/_ChatRoomImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* 08 April 2014 18:54:33 o'clock IST
*/

public abstract class _ChatRoomImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Chat.ChatRoom, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ChatRoomImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerCB", new java.lang.Integer (0));
    _methods.put ("chat", new java.lang.Integer (1));
    _methods.put ("registerGame", new java.lang.Integer (2));
    _methods.put ("homePlay", new java.lang.Integer (3));
    _methods.put ("awayPlay", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Chat methods
       case 0:  // Chat/ChatRoom/registerCB
       {
         Chat.Member m = Chat.MemberHelper.read (in);
         String name = in.read_string ();
         this.registerCB (m, name);
         out = $rh.createReply();
         break;
       }

       case 1:  // Chat/ChatRoom/chat
       {
         String type = in.read_string ();
         String c = in.read_string ();
         String name = in.read_string ();
         this.chat (type, c, name);
         out = $rh.createReply();
         break;
       }


  // Game related methods
       case 2:  // Chat/ChatRoom/registerGame
       {
         Chat.Player p = Chat.PlayerHelper.read (in);
         String name = in.read_string ();
         String $result = null;
         $result = this.registerGame (p, name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // Chat/ChatRoom/homePlay
       {
         String word = in.read_string ();
         this.homePlay (word);
         out = $rh.createReply();
         break;
       }

       case 4:  // Chat/ChatRoom/awayPlay
       {
         String word = in.read_string ();
         String $result = null;
         $result = this.awayPlay (word);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Chat/ChatRoom:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ChatRoomImplBase
