package Chat;


/**
* Chat/ChatRoom_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* 08 April 2014 18:54:33 o'clock IST
*/

public class ChatRoom_Tie extends _ChatRoomImplBase
{

  // Constructors
  public ChatRoom_Tie ()
  {
  }

  public ChatRoom_Tie (Chat.ChatRoomOperations impl)
  {
    super ();
    _impl = impl;
  }


  // Chat methods
  public void registerCB (Chat.Member m, String name)
  {
    _impl.registerCB(m, name);
  } // registerCB

  public void chat (String type, String c, String name)
  {
    _impl.chat(type, c, name);
  } // chat


  // Game related methods
  public String registerGame (Chat.Player p, String name)
  {
    return _impl.registerGame(p, name);
  } // registerGame

  public void homePlay (String word)
  {
    _impl.homePlay(word);
  } // homePlay

  public String awayPlay (String word)
  {
    return _impl.awayPlay(word);
  } // awayPlay

  private Chat.ChatRoomOperations _impl;

} // class ChatRoom_Tie
