package Chat;


/**
* Chat/ChatRoom_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* 04 April 2014 14:45:11 o'clock IST
*/

public class ChatRoom_Tie extends _ChatRoomImplBase
{

  // Constructors
  public ChatRoom_Tie ()
  {
  }

  public ChatRoom_Tie (Chat.ChatRoomOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void registerCB (Chat.Member m, String name)
  {
    _impl.registerCB(m, name);
  } // registerCB

  public String registerGame (Chat.Player p, String name)
  {
    return _impl.registerGame(p, name);
  } // registerGame

  public void chat (String type, String c, String name)
  {
    _impl.chat(type, c, name);
  } // chat

  private Chat.ChatRoomOperations _impl;

} // class ChatRoom_Tie
