package Chat;


/**
* Chat/ChatRoomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* 08 April 2014 18:54:33 o'clock IST
*/

public interface ChatRoomOperations 
{

  // Chat methods
  void registerCB (Chat.Member m, String name);
  void chat (String type, String c, String name);

  // Game related methods
  String registerGame (Chat.Player p, String name);
  void homePlay (String word);
  String awayPlay (String word);
} // interface ChatRoomOperations
