package Chat;


/**
* Chat/MemberOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* 08 April 2014 18:54:33 o'clock IST
*/

public interface MemberOperations 
{
  void callBack (String message);
} // interface MemberOperations
