package Chat;

/**
* Chat/MemberHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* 08 April 2014 18:54:33 o'clock IST
*/

public final class MemberHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.Member value = null;

  public MemberHolder ()
  {
  }

  public MemberHolder (Chat.Member initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.MemberHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.MemberHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.MemberHelper.type ();
  }

}
