package Chat;


/**
* Chat/Player_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* 04 April 2014 14:45:11 o'clock IST
*/

public class Player_Tie extends _PlayerImplBase
{

  // Constructors
  public Player_Tie ()
  {
  }

  public Player_Tie (Chat.PlayerOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void callBack (String message)
  {
    _impl.callBack(message);
  } // callBack

  private Chat.PlayerOperations _impl;

} // class Player_Tie
