package Chat;


/**
* Chat/PlayerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* 04 April 2014 14:45:11 o'clock IST
*/

public interface PlayerOperations 
{
  void callBack (String message);
} // interface PlayerOperations
