package Chat;

/**
* Chat/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* 04 April 2014 14:45:11 o'clock IST
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (Chat.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.PlayerHelper.type ();
  }

}
