package Chat;


/**
* Chat/Player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* 08 April 2014 18:54:33 o'clock IST
*/

public interface Player extends PlayerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Player
