package Chat;


/**
* Chat/Member.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chatroom.idl
* 01 April 2014 19:33:20 o'clock IST
*/

public interface Member extends MemberOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Member
