package Chat;


/**
* Chat/MemberOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chatroom.idl
* 01 April 2014 19:33:20 o'clock IST
*/

public interface MemberOperations 
{
  void callBack (String message);
} // interface MemberOperations
