package Chat;


/**
* Chat/ChatRoom.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chatroom.idl
* 03 April 2014 17:13:14 o'clock IST
*/

public interface ChatRoom extends ChatRoomOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatRoom
