package Chat;


/**
* Chat/ChatRoomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chatroom.idl
* 03 April 2014 17:13:14 o'clock IST
*/

public interface ChatRoomOperations 
{
  void registerCB (Chat.Member m, String name);
  void chat (String c, String name);
} // interface ChatRoomOperations
